<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Activation email' => 'Aktivasyon mail',
    'This email has already been taken.' => 'Bu hesap zaten mevcut',
    'Your account has been successfully activated.' => 'Hesabýnýz aktive edildi',
    'Your account has been successfully created. Check your email for further instructions.' => 'Hesabýnýz baþarýyla oluþturuldu. Lütfen mailinizi kontrol ediniz',
    'Your activation link: {url}' => 'Hesabýnýzý aktive etmek için link:',
    'About' => 'Hakkýmýzda',
    'Account Settings' => 'Hesap ayarlarý',
    'Articles' => 'Konular',
    'Attachments' => 'Ekler',
    'Backend' => 'Beckend',
    'Body' => 'body',
    'Check your email for further instructions.' => 'Detaylý bilgi için mailinizi kontrol edin',
    'Confirm Password' => 'Þifreyi onaylama',
    'Contact' => 'Ýletiþim',
    'E-mail' => 'E-mail',
    'Email' => 'Email',
    'Error while oauth process.' => 'Hata',
    'Female' => 'Bayan',
    'Home' => 'Baþlangýç',
    'If you forgot your password you can reset it <a href="{link}">here</a>' => 'Þifrenizi unuttuysanýz sýfýrlayabilirsiniz <a href="{link}">here</a>',
    'Incorrect username or password.' => 'Geçersiz þifre veya kullanýcý adý',
    'Language' => 'Lisan',
    'Log in with' => 'ile giriþ yapýn',
    'Login' => 'Giriþ',
    'Logout' => 'Çýkýþ',
    'Male' => 'Erkek',
    'Name' => 'Ýsim',
    'Need an account? Sign up.' => 'Hesabýnýz yokmu ? Kayýt olun',
    'New password was saved.' => 'Yeni þifreniz kayýt edildi',
    'Page not found' => 'Sayfa bulunamadý',
    'Password' => 'Þifre',
    'Password reset for {name}' => 'Þifre sýfýrlama {name}',
    'Profile settings' => 'Profil ayarlarý',
    'Remember Me' => 'Beni hatýrla',
    'Request password reset' => 'Þifre sýfýrlama talebi',
    'Reset password' => 'Þifreyi sýfýrla',
    'Settings' => 'Ayarlar',
    'Sign up with' => 'Kayýt için',
    'Signup' => 'Kayýt',
    'Sorry, we are unable to reset password for email provided.' => 'Üzgünüz belirtilen email ile þifreyi sýfýrlayamýyoruz',
    'Subject' => 'Nesne',
    'Submit' => 'Gönder',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'En kýsa zamanda sizinle irtibata geçeceðiz',
    'There was an error sending email.' => 'Email gönderirken hata oluþtu',
    'This email address has already been taken.' => 'Bu email adresi kullanýlmaktadýr',
    'This username has already been taken.' => 'Bu kullanýcý adý mevcut',
    'Update' => 'Güncelle',
    'User Settings' => 'Kullanýcý ayarlarý',
    'Username' => 'Kullanýcý adý',
    'Username or email' => 'Kullanýcý adý veya email ',
    'Verification Code' => 'Onay kodu',
    'We already have a user with email {email}' => 'Bu mail adresi kayýtlýdýr',
    'Welcome to {app-name}. Email with your login information was sent to your email.' => 'Hoþgeldiniz {app-name}. Giriþ bilgileriniz email adresinize gönderilmiþtir',
    'Your account has been successfully saved' => 'Hesabýnýz baþarýyla oluþturuldu',
    '{app-name} | Your login information' => '{app-name} | Giriþ bilgileriniz',
    //added for jassmine
    'Shops' => 'Maðazalar',
    'Franchising' => 'Bayimiz olun',
    'Human Resources' => 'Ýnsan kaynaklarý',
    'Media' =>'Medya',
    'Miss Jassmine' => 'Miss Jassmine',
    'Products' => 'Ürünler',

];
